sonar.projectKey=observeone-cli
sonar.projectName=observeone-cli
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage*/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=e2e/**,examples/**,scripts/**,suites/**,docs/**,src/__tests__/**,src/types/**,**/*.config.*,src/commands/**,src/index.ts
